// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: services/raspberrypi/interact.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type SetAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceName string `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	InterfaceAddr string `protobuf:"bytes,2,opt,name=interfaceAddr,proto3" json:"interfaceAddr,omitempty"`
}

func (x *SetAddrRequest) Reset() {
	*x = SetAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_raspberrypi_interact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddrRequest) ProtoMessage() {}

func (x *SetAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_raspberrypi_interact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddrRequest.ProtoReflect.Descriptor instead.
func (*SetAddrRequest) Descriptor() ([]byte, []int) {
	return file_services_raspberrypi_interact_proto_rawDescGZIP(), []int{0}
}

func (x *SetAddrRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetAddrRequest) GetInterfaceAddr() string {
	if x != nil {
		return x.InterfaceAddr
	}
	return ""
}

// 响应消息
type SetAddrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *SetAddrResponse) Reset() {
	*x = SetAddrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_raspberrypi_interact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddrResponse) ProtoMessage() {}

func (x *SetAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_raspberrypi_interact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddrResponse.ProtoReflect.Descriptor instead.
func (*SetAddrResponse) Descriptor() ([]byte, []int) {
	return file_services_raspberrypi_interact_proto_rawDescGZIP(), []int{1}
}

func (x *SetAddrResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_services_raspberrypi_interact_proto protoreflect.FileDescriptor

var file_services_raspberrypi_interact_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x61, 0x73, 0x70, 0x62,
	0x65, 0x72, 0x72, 0x79, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x5c, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x27, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x4c, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x68, 0x65, 0x66,
	0x61, 0x6e, 0x31, 0x32, 0x33, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x74,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x72, 0x61, 0x73, 0x70, 0x62, 0x65, 0x72, 0x72, 0x79, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_raspberrypi_interact_proto_rawDescOnce sync.Once
	file_services_raspberrypi_interact_proto_rawDescData = file_services_raspberrypi_interact_proto_rawDesc
)

func file_services_raspberrypi_interact_proto_rawDescGZIP() []byte {
	file_services_raspberrypi_interact_proto_rawDescOnce.Do(func() {
		file_services_raspberrypi_interact_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_raspberrypi_interact_proto_rawDescData)
	})
	return file_services_raspberrypi_interact_proto_rawDescData
}

var file_services_raspberrypi_interact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_raspberrypi_interact_proto_goTypes = []any{
	(*SetAddrRequest)(nil),  // 0: protobuf.SetAddrRequest
	(*SetAddrResponse)(nil), // 1: protobuf.SetAddrResponse
}
var file_services_raspberrypi_interact_proto_depIdxs = []int32{
	0, // 0: protobuf.Interact.SetAddr:input_type -> protobuf.SetAddrRequest
	1, // 1: protobuf.Interact.SetAddr:output_type -> protobuf.SetAddrResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_raspberrypi_interact_proto_init() }
func file_services_raspberrypi_interact_proto_init() {
	if File_services_raspberrypi_interact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_raspberrypi_interact_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_raspberrypi_interact_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetAddrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_raspberrypi_interact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_raspberrypi_interact_proto_goTypes,
		DependencyIndexes: file_services_raspberrypi_interact_proto_depIdxs,
		MessageInfos:      file_services_raspberrypi_interact_proto_msgTypes,
	}.Build()
	File_services_raspberrypi_interact_proto = out.File
	file_services_raspberrypi_interact_proto_rawDesc = nil
	file_services_raspberrypi_interact_proto_goTypes = nil
	file_services_raspberrypi_interact_proto_depIdxs = nil
}
